apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  minReadySeconds: 20
  replicas: 5
  template:
    spec:
      containers:
      - name: vote
        image: zhuahaha/vote:v3 # {“$imagepolicy”: “flux-system:vote”}
