apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
spec:
  minReadySeconds: 20
  replicas: 3
  template:
    spec:
      containers:
      - name: vote
        image: schoolofdevops/vote:v4
