apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  minReadySeconds: 20
  replicas: 4
  template:
    spec:
      containers:
      - name: vote
        image: schoolofdevops/vote:v3
